#!/usr/bin/env bash

DESTINATION=$HOME/.local/bin

FLAGS=()

help() {
    echo "Usage: install [?OPTIONS]"
    echo "Install vmhelper"
    echo "Options:"
    echo "  -h, --help              Display this message"
    echo "  -g, --global            Fuzzy get all VM names"
    echo "  -v, --verbose           Fuzzy get inactive VM name"
    exit 0
}

get_file_directory() {
    FULL_FILEPATH=$(readlink -f "$1")
    FILE_DIRECTORY=$(dirname "$FULL_FILEPATH")
    echo "$FILE_DIRECTORY"
}

create_completion_file() {
    cat >"$HOME"/.bash_completion <<'EOF'
for bcfile in ~/.bash_completion.d/*; do
    . "$bcfile"
done
EOF
}

main() {
    while [[ "$#" -gt 0 ]]; do
        case $1 in
        -h | --help) help ;;
        -g | --global)
            # for non distribution-managed programs
            DESTINATION=/usr/local/bin
            ;;
        -v | --verbose)
            FLAGS+=(-v)
            ;;
        undefined) ;;
        *)
            echo "invalid option $1"
            exit 1
            ;;
        esac
        shift
    done

    local base_directory source_ target completion_file completion_dir

    base_directory=$(get_file_directory "${BASH_SOURCE[0]}")
    source_="$base_directory"/bin/vmhelper
    target="$DESTINATION"/vmhelper

    install "${FLAGS[@]}" "$source_" "$target"

    completion_file=$HOME/.bash_completion
    completion_dir=$HOME/.bash_completion.d

    if [[ ! -f $completion_file ]]; then
        create_completion_file
    fi

    mkdir -p "$completion_dir"
    cp ./completion/vmhelper_completion "$completion_dir"

    return 0
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
