#!/usr/bin/env bash

get() {
    local VM
    local MAC

    case "$1" in
    -h | --help)
        echo "Usage: vmhelper get [?OPTION]"
        echo "If no option is selected, default to active VM names"
        echo "Commands:"
        echo "  -h, --help              Display this message"
        echo "  --all                   Fuzzy get all VM names"
        echo "  --inactive              Fuzzy get inactive VM name"
        echo "  --active                Fuzzy get active VM name"
        echo "  --ip                    Fuzzy get VM ip"
        echo "  --snapshot              Fuzzy get snapshot name for VM"
        ;;
    --all)
        echo -n "$(virsh list --all --name | fzf)"
        ;;
    --inactive)
        # echo -n "$(virsh list --all --inactive --name | fzf)"
        echo -n "$(virsh list --all --inactive --name | fzf)"
        ;;
    --active)
        # echo -n "$(virsh list --all --inactive --name | fzf)"
        echo -n "$(virsh list --name | fzf)"
        ;;
    --ip)
        VM="$(virsh list --name | fzf)"
        if [[ -n $VM ]]; then
            MAC=$(virsh domiflist "$VM" | awk 'NR>2 {print $5}')
            echo -n "$(virsh net-dhcp-leases default | awk -v m="$MAC" '$3 == m {print $5}' | cut -d/ -f1)"
        fi
        ;;
    --snapshot)
        shift
        VM="$1"
        if [[ -z "$VM" ]]; then
            VM="$(get --all)"
        fi

        if [[ -n $VM ]]; then
            echo -n "$(virsh snapshot-list --name "$VM" | fzf)"
        fi
        ;;
    *)
        echo -n "$(virsh list --name | fzf)"
        ;;
    esac
}

ssh-vm() {
    local USERNAME
    local IP

    while [[ "$#" -gt 0 ]]; do
        case "$1" in
        -h | --help)
            echo "Usage: vmhelper ssh-vm [?OPTION] [USERNAME]"
            echo "Commands:"
            echo "  -h, --help              Display this message"
            echo "  USERNAME                Username to connect with to VM"
            exit 0
            ;;
        *)
            USERNAME=$1
            ;;
        esac
        shift
    done

    if [[ -z $USERNAME ]]; then
        echo "no username provided"
    fi

    IP=$(get --ip)

    if [[ -n $IP ]]; then
        ssh "$USERNAME@$IP"
    fi
}

ssh-copy() {
    local USERNAME
    while [[ "$#" -gt 0 ]]; do
        case "$1" in
        -h | --help)
            echo "Usage: vmhelper ssh-copy [?OPTION] [USERNAME]"
            echo "Commands:"
            echo "  -h, --help              Display this message"
            echo "  USERNAME                Username to copy to on VM"
            exit 0
            ;;
        *)
            USERNAME=$1
            ;;
        esac
        shift
    done

    if [[ -z $USERNAME ]]; then
        echo "no username selected"
        exit
    fi
    ssh-copy-id "$USERNAME@$(get --ip)"
}

create-snapshot() {
    local VM
    local DESCRIPTION
    local SNAPSHOT_NAME

    while [[ "$#" -gt 0 ]]; do
        case $1 in
        -h | --help)
            echo "Usage: vmhelper create-snapshot [?OPTION]"
            echo "Commands:"
            echo "  -h, --help              Display this message"
            echo "  --description           Snapshot Description"
            echo "  --snapshot-name         Snapshot Name"
            exit 0
            ;;
        -d | --description)
            shift
            DESCRIPTION="$1"
            ;;
        -s | --snapshot-name)
            shift
            SNAPSHOT_NAME="$1"
            ;;
        esac
        shift
    done

    if [[ -z $DESCRIPTION ]]; then
        read -rp "Enter Description: " DESCRIPTION
    fi

    if [[ -z $SNAPSHOT_NAME ]]; then
        read -rp "Enter Snapshot Name: " SNAPSHOT_NAME
    fi

    VM=$(get --active)

    if [[ -n $DESCRIPTION ]] && [[ -n $VM ]] && [[ -n $SNAPSHOT_NAME ]]; then
        virsh snapshot-create-as \
            --description "$DESCRIPTION" "$VM" "$SNAPSHOT_NAME"
    fi
}

rollback-snapshot() {
    local VM
    local SNAPSHOT
    local CHOICE

    while [[ "$#" -gt 0 ]]; do
        case $1 in
        -h | --help)
            echo "Usage: vmhelper rollback-snapshot [?OPTION]"
            echo "Commands:"
            echo "  -h, --help              Display this message"
            echo "  -y                      Accept"
            echo "  --virtual-machine       Virtual machine name"
            echo "  --snapshot-name         Snapshot Name"
            exit 0
            ;;
        --virtual-machine)
            shift
            VM=$1
            ;;
        --snapshot-name)
            shift
            SNAPSHOT=$1
            ;;
        -y)
            CHOICE='y'
            ;;
        esac
        shift
    done

    if [[ -z $VM ]]; then
        VM="$(get --active)"
    fi

    if [[ -z $SNAPSHOT ]]; then
        SNAPSHOT="$(get --snapshot "$VM")"
    fi

    echo "reverting $VM to $SNAPSHOT"

    if [[ -z $CHOICE ]]; then
        CHOICE=''
    fi

    while [[ $CHOICE != "y" ]] && [[ $CHOICE != "n" ]]; do
        read -rp "proceed [y]es/[n]o: " CHOICE
        CHOICE="${CHOICE:0:1}"
        CHOICE="${CHOICE,,}"
        if [[ $CHOICE != "y" ]] && [[ $CHOICE != "n" ]]; then
            echo "choice should be either [y]es/[n]o"
        fi
    done

    if [[ $CHOICE == 'y' ]]; then
        echo "running: virsh snapshot-revert $VM $SNAPSHOT"
        virsh snapshot-revert "$VM" "$SNAPSHOT"
    else
        echo 'revert cancelled'
    fi
    exit 0
}

while [[ "$#" -gt 0 ]]; do
    case "$1" in
    -h | --help)
        echo "Usage: vmhelper [?OPTION] [COMMAND]"
        echo "Commands:"
        echo "  -h, --help                      Display this message"
        echo "  get [OPTIONS]                   Get vm information"
        echo "  start                           Start a VM"
        echo "  shutdown                        Shutdown a VM"
        echo "  attach                          Attach to a VM though the console"
        echo "  ssh [OPTIONS] [?USERNAME]       SSH into a vm"
        echo "  ssh-copy [?IP_ADDRESS]          Copy RSA key to vm"
        echo "  create-snapshot [OPTIONS]       Create a snapshot for a VM"
        echo "  rollback-snapshot [OPTIONS]     Rollback to VM snapshot"
        exit 0
        ;;
    get)
        shift
        get "$@"
        exit 0
        ;;
    start)
        shift
        virsh start "$(get --inactive)"
        exit 0
        ;;
    shutdown)
        shift
        virsh shutdown "$(get --active)"
        exit 0
        ;;
    attach)
        shift
        virsh console "$(get --active)"
        exit 0
        ;;
    ssh)
        shift
        ssh-vm "$@"
        exit 0
        ;;
    ssh-copy)
        shift
        ssh-copy "$@"
        exit 0
        ;;
    create-snapshot)
        shift
        create-snapshot "$@"
        exit 0
        ;;
    rollback-snapshot)
        shift
        rollback-snapshot "$@"
        ;;
    esac
    shift
done
